apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-booth-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-booth-volume
  template:
    metadata:
      labels:
        app: mqtt-booth-volume
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
        - name: mqtt-booth-volume
          image: ghcr.io/fermyon/spin-mqtt-booth-volume:latest
          imagePullPolicy: IfNotPresent
          command: ["/"]
          ports:
          - containerPort: 80
          env:
          - name: SPIN_VARIABLE_MQTT_TOPIC
            value: "booth/+"
          - name: SPIN_VARIABLE_MQTT_BROKER_URI
            value: "mqtt://BROKER_IP:1883"
          # - name: SPIN_VARIABLE_SQLITE_USERNAME
          #   value: "admin"
          # - name: SPIN_VARIABLE_SQLITE_PASSWORD
          #   value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-booth-volume
spec:
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mqtt-booth-volume
